[package]
name = "accrete"
version = "0.1.0"
authors = ["Leonid <leonidgrr@gmail.com>"]
license="MIT OR Apache-2.0"
repository = "https://github.com/LeonidGrr/accrete.git"
description="Rust port of Accrete, planetary system accretion simulation algorithm by Stephen H. Dole, published as 'Formation of Planetary Systems by Aggregation: A Computer Simulation'."
edition = "2018"
readme = "README.md"
keywords = ["accrete", "planetary", "system", "procedural", "generation"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
