[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accrete = { path = "../.." }
bevy = "0.6"

[profile.dev.package.'*']
opt-level = 3

[workspace]
resolver = "2"